from pydantic import BaseModel, Field


class CreateCandidateProfileRequest(BaseModel):
    candidate_name: str = Field(
        default="Candidate",
        min_length=1,
        max_length=100,
    )

    resume_text: str = Field(
        ...,
        min_length=50,
        max_length=50000,
    )

    profile: dict = Field(
        ...,
        description="Structured candidate profile generated by the candidate analyzer.",
    )


class CandidateProfileResponse(BaseModel):
    candidate_id: int
    candidate_name: str
    profile: dict
class ProcessCandidateRequest(BaseModel):
    candidate_name: str = Field(
        default="Candidate",
        min_length=1,
        max_length=100,
    )

    resume_text: str = Field(
        ...,
        min_length=50,
        max_length=50000,
    )

    job_description: str = Field(
        ...,
        min_length=50,
        max_length=30000,
    )